Update

diff --git a/.config/bash/aliases b/.config/bash/aliases
--- a/.config/bash/aliases
+++ b/.config/bash/aliases
@@ -15,8 +15,10 @@ if command -v zoxide &> /dev/null; then
       builtin cd "$HOME" && return
     elif [ -d "$1" ]; then
       builtin cd "$1"
+    elif declare -f __zoxide_z >/dev/null; then
+      __zoxide_z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
     else
-      z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+      echo "Error: zoxide is not initialized"
     fi
   }
 fi
